### ISSUE TITLE
Copper zone issue with USB_Micro-B_Molex-105017-0001

### ISSUE THREAD

**Issue by forkineye** [KiCad/Connectors_USB.pretty#9]
One of the THT pads for USB_Micro-B_Molex-105017-0001 is set to "none" instead of "From parent footprint"
![Imgur](http://i.imgur.com/V6pE0XE.png)

**Comment by poeschlr** [comment]
Would you care to create a pull request that corrects this?

**Comment by forkineye** [comment]
PR submitted https://github.com/KiCad/Connectors_USB.pretty/pull/10
